### PR TITLE
update template to use hasBlock

### LINKED ISSUE #2: Accessing 'template' in component button-option is deprecated.
To determine if a block was specified to please use '{{#if hasBlock}}' in the components layout.

### PR DESCRIPTION
**Pull request by JonathanPrince**
fixes #2

### CODE REVIEW

**Comment by jasonkriss** [comment]
Awesome. Thanks for taking care of that @JonathanPrince!

**Comment by JonathanPrince** [comment]
No worries, thank you for the cool component

**Comment by JonathanPrince** [comment]
Hi @jasonkriss, could you please publish to NPM when you get time?

**Comment by jasonkriss** [comment]
Absolutely. Just released v0.3.0. Sorry about that!

**Comment by JonathanPrince** [comment]
Thank you!

**Pull request merged**
